/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ls.jtsk.ui;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import ls.jtsk.helper.CustomerHelper;
import ls.jtsk.model.Customer;
import ls.jtsk.ui.controller.CentralController;
import ls.jtsk.util.NetID;
/**
 *
 * @author LS
 */
public class ActivateWindow extends javax.swing.JFrame {

    /**
     * Creates new form ActivateWindow
     */
    public ActivateWindow() {
        initComponents();
        String s = getWelcomeString();
        if (s.length() > 0) {
            disableAllInputBoxAndEnable(s);
        }
    }

    /**
     * 校验是否激活，如果激活返回欢迎信息，否则返回空。
     * 我们同时利用这个函数来作为判断标识。
     * @return 
     */
    private String getWelcomeString() {
        String welcomeString = ""; 
        Customer c = CustomerHelper.getFirstCustomer();
        if ( c != null) {
            if (c.getIsActivated() == 1) { 
                welcomeString = "欢迎您，"+c.getHospitalAndDepString()+c.getName()+"。您已经激活，请点击下面按钮进入";
            }
        }
        return welcomeString;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        enterApgarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputActivateContinueButton = new javax.swing.JButton();
        hosInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        generateApplyButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        doctorInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        actInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        snLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setText("第二步");

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setText("第三步");

        jLabel3.setText("已获得激活码的用户，请输入并继续");

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setText("第一步");

        welcomeLabel.setForeground(new java.awt.Color(102, 153, 0));
        welcomeLabel.setText("您已经激活");
        welcomeLabel.setEnabled(false);

        enterApgarButton.setText("进入apgar自动评分仪");
        enterApgarButton.setActionCommand("进入阿氏评分法自动评分仪");
        enterApgarButton.setEnabled(false);
        enterApgarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterApgarButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("请输入激活码");

        inputActivateContinueButton.setText("输入激活码并继续");
        inputActivateContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActivateContinueButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("医院科室");

        generateApplyButton.setText("生成序列号");
        generateApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateApplyButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("大夫");

        jLabel4.setText("请输入信息，生成激活申请号，发给刘大夫获取激活码");

        jLabel7.setText("激活申请号");

        snLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(59, 59, 59)
                                .addComponent(snLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterApgarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputActivateContinueButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateApplyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(welcomeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(hosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(doctorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateApplyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(snLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(actInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(inputActivateContinueButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterApgarButton)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActivateContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActivateContinueButtonActionPerformed
    
        if (actInput.getText() != null && actInput.getText().trim().length() > 0) {
            try {
                long userInputActivateSN = Long.parseLong(actInput.getText().trim());
                if (NetID.isValidActivateNumber(userInputActivateSN)) {
                    enterApgarButton.setEnabled(true);
                    CustomerHelper.updateCustomerWithActivated(1);
                    String s = getWelcomeString();
                    if (s.length() > 0) {
                        disableAllInputBoxAndEnable(s);
                    }
                } else {
                    CentralController.showCommonMessageBox("激活码错误，请核实并输入正确的9位激活码");
                }
            }
            catch (Exception e) {
                e.printStackTrace();
                CentralController.showCommonMessageBox("激活码错误，请核实并输入正确的9位激活码");
            }

        }
        else {
            CentralController.showCommonMessageBox("请核实并输入正确的9位激活码");
        }
    }//GEN-LAST:event_inputActivateContinueButtonActionPerformed

    private void generateApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateApplyButtonActionPerformed
        if (hosInput.getText() != null && doctorInput.getText() != null && doctorInput.getText().trim().length() > 0 && hosInput.getText().trim().length() > 0) {
            snLabel.setText(new Long(NetID.generateApplyNumber()).toString());
            CustomerHelper.addNewCustomer(hosInput.getText(), doctorInput.getText(), null, null, null);
//            snLabel.setVisible(true);
//          当正式运行时，需要删掉
//            actInput.setText(NetID.finalActivateNumberGenerate(NetID.generateApplyNumber()));
        } else {
            snLabel.setText("");
            CentralController.showCommonMessageBox("请正确输入医院科室信息和使用者信息");
//            snLabel.setVisible(false);
        }

    }//GEN-LAST:event_generateApplyButtonActionPerformed

    private void enterApgarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterApgarButtonActionPerformed
        this.dispose();
        CaseHistory ch = new CaseHistory();
        ch.setLocationRelativeTo(null);
        ch.setVisible(true);
    }//GEN-LAST:event_enterApgarButtonActionPerformed

    private void snLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snLabelActionPerformed

    private void disableAllInputBoxAndEnable(String welcomeStr) {
        hosInput.setEnabled(false);
        doctorInput.setEnabled(false);
        generateApplyButton.setEnabled(false);
        actInput.setEnabled(false);
        inputActivateContinueButton.setEnabled(false);
        enterApgarButton.setEnabled(true);
        welcomeLabel.setEnabled(true);
        welcomeLabel.setText(welcomeStr);
        snLabel.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivateWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actInput;
    private javax.swing.JTextField doctorInput;
    private javax.swing.JButton enterApgarButton;
    private javax.swing.JButton generateApplyButton;
    private javax.swing.JTextField hosInput;
    private javax.swing.JButton inputActivateContinueButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField snLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
