/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ls.jtsk.ui;

import java.awt.event.ActionEvent;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import ls.jtsk.helper.ApgarHelper;
import ls.jtsk.model.Apgar;
import ls.jtsk.ui.assistant.ApgarFactory;
import ls.jtsk.ui.controller.CentralController;
import ls.jtsk.ui.timer.ApgarTimer;

/**
 *
 * @author liushuai
 */
public class APGARTab extends javax.swing.JFrame {
    long momId, babyId;
    /**
     * Creates new form APGAR
     */
    public APGARTab(long momId, long babyId) {
        initComponents();
        ApgarTimer.registerDisplayComponent(apgarTimerLabel);
        this.momId = momId;
        this.babyId = babyId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xinLvOneminButtonGroup1 = new javax.swing.ButtonGroup();
        huXiOneminButtonGroup = new javax.swing.ButtonGroup();
        jiZhangLiOneminButtonGroup = new javax.swing.ButtonGroup();
        ciJiOneminButtonGroup = new javax.swing.ButtonGroup();
        fuSeOneMinButtonGroup = new javax.swing.ButtonGroup();
        fiveMinPulsebuttonGroup = new javax.swing.ButtonGroup();
        fiveMinRespirationButtonGroup = new javax.swing.ButtonGroup();
        fiveMinActivityButtonGroup = new javax.swing.ButtonGroup();
        fiveMinGrimaceButtonGroup = new javax.swing.ButtonGroup();
        fiveMinAppearanceButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        apgarTimerLabel = new javax.swing.JLabel();
        jRadioButton61 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton77 = new javax.swing.JRadioButton();
        tenMinTotalLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jRadioButton76 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        oneMinTotalLabel = new javax.swing.JLabel();
        fiveMinTotalLabel = new javax.swing.JLabel();
        oneMinConfirmButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        xinLvOneminButtonGroup1.add(jRadioButton55);
        jRadioButton55.setText("1");
        jRadioButton55.setActionCommand("1_pulse_1");
        jRadioButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton55ActionPerformed(evt);
            }
        });

        xinLvOneminButtonGroup1.add(jRadioButton54);
        jRadioButton54.setText("0");
        jRadioButton54.setActionCommand("1_pulse_0");
        jRadioButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton54ActionPerformed(evt);
            }
        });

        xinLvOneminButtonGroup1.add(jRadioButton56);
        jRadioButton56.setText("2");
        jRadioButton56.setActionCommand("1_pulse_2");
        jRadioButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton56ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel14.setText("心率(次/分)");

        jLabel18.setText("0：无");

        jLabel19.setText("1：小于100");

        jLabel20.setText("2：大于等于100");

        jLabel22.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel22.setText("1分钟");

        jLabel23.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel23.setText("10分钟");

        jLabel25.setText("2：规则、哭声洪亮");

        jLabel28.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel28.setText("对刺激反应、怪象");

        jLabel29.setText("0：无");

        jLabel30.setText("1：慢、不规则");

        jLabel34.setText("2：四肢活动好");

        jLabel36.setText("0：松弛");

        huXiOneminButtonGroup.add(jRadioButton21);
        jRadioButton21.setText("0");
        jRadioButton21.setActionCommand("1_respiration_0");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        huXiOneminButtonGroup.add(jRadioButton22);
        jRadioButton22.setText("1");
        jRadioButton22.setActionCommand("1_respiration_1");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        huXiOneminButtonGroup.add(jRadioButton23);
        jRadioButton23.setText("2");
        jRadioButton23.setActionCommand("1_respiration_2");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton24);
        jRadioButton24.setText("0");
        jRadioButton24.setActionCommand("10_respiration_0");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton25);
        jRadioButton25.setText("1");
        jRadioButton25.setActionCommand("10_respiration_1");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton26);
        jRadioButton26.setText("2");
        jRadioButton26.setActionCommand("10_respiration_2");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jiZhangLiOneminButtonGroup.add(jRadioButton27);
        jRadioButton27.setText("0");
        jRadioButton27.setActionCommand("1_activity_0");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        jiZhangLiOneminButtonGroup.add(jRadioButton28);
        jRadioButton28.setText("1");
        jRadioButton28.setActionCommand("1_activity_1");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });

        jiZhangLiOneminButtonGroup.add(jRadioButton29);
        jRadioButton29.setText("2");
        jRadioButton29.setActionCommand("1_activity_2");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton31);
        jRadioButton31.setText("0");
        jRadioButton31.setActionCommand("10_activity_0");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton49);
        jRadioButton49.setText("2");
        jRadioButton49.setActionCommand("10_activity_2");
        jRadioButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton49ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton50);
        jRadioButton50.setText("1");
        jRadioButton50.setActionCommand("10_activity_1");
        jRadioButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton50ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton53);
        jRadioButton53.setText("1");
        jRadioButton53.setActionCommand("10_pulse_1");
        jRadioButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton53ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton52);
        jRadioButton52.setText("2");
        jRadioButton52.setActionCommand("10_pulse_2");
        jRadioButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton52ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton58);
        jRadioButton58.setText("0");
        jRadioButton58.setActionCommand("10_pulse_0");
        jRadioButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton58ActionPerformed(evt);
            }
        });

        jLabel37.setText("1：四肢屈曲");

        apgarTimerLabel.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        apgarTimerLabel.setText("00:00");

        ciJiOneminButtonGroup.add(jRadioButton61);
        jRadioButton61.setText("0");
        jRadioButton61.setActionCommand("1_grimace_0");
        jRadioButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton61ActionPerformed(evt);
            }
        });

        ciJiOneminButtonGroup.add(jRadioButton60);
        jRadioButton60.setText("1");
        jRadioButton60.setActionCommand("1_grimace_1");
        jRadioButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton60ActionPerformed(evt);
            }
        });

        ciJiOneminButtonGroup.add(jRadioButton68);
        jRadioButton68.setText("2");
        jRadioButton68.setActionCommand("1_grimace_2");
        jRadioButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton68ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton62);
        jRadioButton62.setText("1");
        jRadioButton62.setActionCommand("10_grimace_1");
        jRadioButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton62ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton63);
        jRadioButton63.setText("2");
        jRadioButton63.setActionCommand("10_grimace_2");
        jRadioButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton63ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton66);
        jRadioButton66.setText("0");
        jRadioButton66.setActionCommand("10_grimace_0");
        jRadioButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton66ActionPerformed(evt);
            }
        });

        jLabel35.setText("2：喷嚏、哭");

        jLabel39.setText("1：略有反应(怪脸、弱反应) ");

        jLabel38.setText("0：无反应");

        jLabel31.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel31.setText("呼吸");

        jLabel32.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel32.setText("肌张力");

        jLabel33.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel33.setText("肤色");

        jLabel40.setText("0：全身青紫或苍白");

        jLabel41.setText("1：躯干红、四肢紫(灰)");

        buttonGroup5.add(jRadioButton69);
        jRadioButton69.setText("2");
        jRadioButton69.setActionCommand("10_appearance_2");
        jRadioButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton69ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButton70);
        jRadioButton70.setText("1");
        jRadioButton70.setActionCommand("10_appearance_1");
        jRadioButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton70ActionPerformed(evt);
            }
        });

        fuSeOneMinButtonGroup.add(jRadioButton71);
        jRadioButton71.setText("0");
        jRadioButton71.setActionCommand("1_appearance_0");
        jRadioButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton71ActionPerformed(evt);
            }
        });

        fuSeOneMinButtonGroup.add(jRadioButton72);
        jRadioButton72.setText("2");
        jRadioButton72.setActionCommand("1_appearance_2");
        jRadioButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton72ActionPerformed(evt);
            }
        });

        fuSeOneMinButtonGroup.add(jRadioButton73);
        jRadioButton73.setText("1");
        jRadioButton73.setActionCommand("1_appearance_1");
        jRadioButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton73ActionPerformed(evt);
            }
        });

        jLabel42.setText("2：粉红色");

        buttonGroup5.add(jRadioButton77);
        jRadioButton77.setText("0");
        jRadioButton77.setActionCommand("10_appearance_0");
        jRadioButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton77ActionPerformed(evt);
            }
        });

        tenMinTotalLabel.setFont(new java.awt.Font("宋体", 1, 60)); // NOI18N
        tenMinTotalLabel.setText("0");

        jLabel44.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel44.setText("总分");

        fiveMinActivityButtonGroup.add(jRadioButton76);
        jRadioButton76.setText("1");
        jRadioButton76.setActionCommand("5_activity_1");
        jRadioButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton76ActionPerformed(evt);
            }
        });

        fiveMinPulsebuttonGroup.add(jRadioButton51);
        jRadioButton51.setText("0");
        jRadioButton51.setActionCommand("5_pulse_0");
        jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton51ActionPerformed(evt);
            }
        });

        fiveMinActivityButtonGroup.add(jRadioButton75);
        jRadioButton75.setText("0");
        jRadioButton75.setActionCommand("5_activity_0");
        jRadioButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton75ActionPerformed(evt);
            }
        });

        fiveMinPulsebuttonGroup.add(jRadioButton59);
        jRadioButton59.setText("1");
        jRadioButton59.setActionCommand("5_pulse_1");
        jRadioButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton59ActionPerformed(evt);
            }
        });

        fiveMinPulsebuttonGroup.add(jRadioButton57);
        jRadioButton57.setText("2");
        jRadioButton57.setActionCommand("5_pulse_2");
        jRadioButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton57ActionPerformed(evt);
            }
        });

        fiveMinGrimaceButtonGroup.add(jRadioButton30);
        jRadioButton30.setText("2");
        jRadioButton30.setActionCommand("5_grimace_2");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        fiveMinGrimaceButtonGroup.add(jRadioButton32);
        jRadioButton32.setText("0");
        jRadioButton32.setActionCommand("5_grimace_0");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });

        fiveMinGrimaceButtonGroup.add(jRadioButton48);
        jRadioButton48.setText("1");
        jRadioButton48.setActionCommand("5_grimace_1");
        jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton48ActionPerformed(evt);
            }
        });

        fiveMinRespirationButtonGroup.add(jRadioButton18);
        jRadioButton18.setText("0");
        jRadioButton18.setActionCommand("5_respiration_0");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        fiveMinRespirationButtonGroup.add(jRadioButton20);
        jRadioButton20.setText("2");
        jRadioButton20.setActionCommand("5_respiration_2");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        fiveMinRespirationButtonGroup.add(jRadioButton19);
        jRadioButton19.setText("1");
        jRadioButton19.setActionCommand("5_respiration_1");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel21.setText("5分钟");

        fiveMinAppearanceButtonGroup.add(jRadioButton67);
        jRadioButton67.setText("2");
        jRadioButton67.setActionCommand("5_appearance_2");
        jRadioButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton67ActionPerformed(evt);
            }
        });

        fiveMinAppearanceButtonGroup.add(jRadioButton64);
        jRadioButton64.setText("0");
        jRadioButton64.setActionCommand("5_appearance_0");
        jRadioButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton64ActionPerformed(evt);
            }
        });

        fiveMinAppearanceButtonGroup.add(jRadioButton65);
        jRadioButton65.setText("1");
        jRadioButton65.setActionCommand("5_appearance_1");
        jRadioButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton65ActionPerformed(evt);
            }
        });

        fiveMinActivityButtonGroup.add(jRadioButton74);
        jRadioButton74.setText("2");
        jRadioButton74.setActionCommand("5_activity_2");
        jRadioButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton74ActionPerformed(evt);
            }
        });

        oneMinTotalLabel.setFont(new java.awt.Font("宋体", 1, 60)); // NOI18N
        oneMinTotalLabel.setText("0");

        fiveMinTotalLabel.setFont(new java.awt.Font("宋体", 1, 60)); // NOI18N
        fiveMinTotalLabel.setText("0");

        oneMinConfirmButton.setText("确定");

        jButton2.setText("确定");

        jButton3.setText("确定");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel31))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel44)
                        .addGap(129, 129, 129)
                        .addComponent(oneMinTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(184, 184, 184))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oneMinConfirmButton)
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addGap(49, 49, 49)
                .addComponent(jButton3)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apgarTimerLabel)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20)
                    .addComponent(jLabel37)
                    .addComponent(jLabel19)
                    .addComponent(jLabel36)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28)
                    .addComponent(jLabel32)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel33)
                    .addComponent(jLabel42))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton61)
                    .addComponent(jRadioButton60)
                    .addComponent(jRadioButton56)
                    .addComponent(jRadioButton68)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton54)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton27)
                    .addComponent(jLabel22)
                    .addComponent(jRadioButton71)
                    .addComponent(jRadioButton72)
                    .addComponent(jRadioButton73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jRadioButton51)
                            .addComponent(jRadioButton57)
                            .addComponent(jRadioButton59))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel23))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton53)
                                    .addComponent(jRadioButton52)
                                    .addComponent(jRadioButton58)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton67)
                            .addComponent(jRadioButton64)
                            .addComponent(jRadioButton65)
                            .addComponent(jRadioButton74)
                            .addComponent(jRadioButton76)
                            .addComponent(jRadioButton75)
                            .addComponent(jRadioButton32)
                            .addComponent(jRadioButton48)
                            .addComponent(jRadioButton30)
                            .addComponent(fiveMinTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton19))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton25)
                            .addComponent(jRadioButton26)
                            .addComponent(jRadioButton24)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton31)
                                        .addComponent(jRadioButton49)
                                        .addComponent(jRadioButton50)
                                        .addComponent(jRadioButton63)
                                        .addComponent(jRadioButton62)
                                        .addComponent(jRadioButton66)
                                        .addComponent(jRadioButton77)
                                        .addComponent(jRadioButton69)
                                        .addComponent(jRadioButton70))
                                    .addGap(120, 120, 120))
                                .addComponent(tenMinTotalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(apgarTimerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton54)
                            .addComponent(jLabel18))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton55)
                            .addComponent(jLabel19))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton56)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jRadioButton51)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton59)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton57))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton58)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton53)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton52)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton21)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton22)
                            .addComponent(jLabel30))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jRadioButton23))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jRadioButton27))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jRadioButton28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jRadioButton29))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton61)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton60)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton68)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jRadioButton71))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jRadioButton73))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton72)
                            .addComponent(jLabel42))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel44))
                            .addComponent(oneMinTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oneMinConfirmButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton25)
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButton26))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton19)
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButton20)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton31)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton75)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton76)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton74)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton30)
                                .addGap(51, 51, 51)
                                .addComponent(jRadioButton64)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton65)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton67)
                                .addGap(32, 32, 32)
                                .addComponent(fiveMinTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButton66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton63)
                                .addGap(53, 53, 53)
                                .addComponent(jRadioButton77)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton70)
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButton69)
                                .addGap(32, 32, 32)
                                .addComponent(tenMinTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(32, 32, 32))
        );

        jLabel14.getAccessibleContext().setAccessibleName("心率");

        finishButton.setText("完成");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("退出");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(405, 405, 405)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton65ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton65ActionPerformed

    private void jRadioButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton64ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton64ActionPerformed

    private void jRadioButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton67ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton67ActionPerformed

    private void jRadioButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton66ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton66ActionPerformed

    private void jRadioButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton63ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton63ActionPerformed

    private void jRadioButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton62ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton62ActionPerformed

    private void jRadioButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton68ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton68ActionPerformed

    private void jRadioButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton60ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton60ActionPerformed

    private void jRadioButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton61ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton61ActionPerformed

    private void jRadioButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton56ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton56ActionPerformed

    private void jRadioButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton57ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton57ActionPerformed

    private void jRadioButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton58ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton58ActionPerformed

    private void jRadioButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton59ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton59ActionPerformed

    private void jRadioButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton51ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton51ActionPerformed

    private void jRadioButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton52ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton52ActionPerformed

    private void jRadioButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton53ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton53ActionPerformed

    private void jRadioButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton55ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton55ActionPerformed

    private void jRadioButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton50ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton50ActionPerformed

    private void jRadioButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton49ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton49ActionPerformed

    private void jRadioButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton48ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton48ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton69ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton69ActionPerformed

    private void jRadioButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton70ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton70ActionPerformed

    private void jRadioButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton71ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton71ActionPerformed

    private void jRadioButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton72ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton72ActionPerformed

    private void jRadioButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton73ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton73ActionPerformed

    private void jRadioButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton74ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton74ActionPerformed

    private void jRadioButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton75ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton75ActionPerformed

    private void jRadioButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton76ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton76ActionPerformed

    private void jRadioButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton77ActionPerformed
       actionHandle(evt);
    }//GEN-LAST:event_jRadioButton77ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jRadioButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton54ActionPerformed
        actionHandle(evt);
    }//GEN-LAST:event_jRadioButton54ActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // save the model from model/view layer to persistent/database layer
        ApgarFactory apgarFactory = ApgarFactory.getApgarFactory();
        CentralController.saveApgarAndDisposeWindow(momId, babyId, apgarFactory.getAllApgars(), this);
    }//GEN-LAST:event_finishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APGARTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APGARTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APGARTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APGARTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APGARTab(0, 0).setVisible(true);
            }
        });
    }
    
    private void actionHandle(ActionEvent e) { // update the model
        String[] splitApgarTags = e.getActionCommand().split("_");
        if (splitApgarTags != null && splitApgarTags[0] != null) {
             ApgarFactory apgarFactory = ApgarFactory.getApgarFactory();
             Apgar apgar = apgarFactory.getApgarByInterval(Integer.parseInt(splitApgarTags[0]));
             
             // 通过从radiobutton中传入的apgar评分类型，比如pulse或者activity，基于反射机制，而不是静态switch判断，直接调用setPulse或者setActivity方法
             Method[] apgarMethods = apgar.getClass().getMethods();
             for (int i=0; i<apgarMethods.length; i++) {
                 if (apgarMethods[i].getName().indexOf("set") != -1 && apgarMethods[i].getName().indexOf(splitApgarTags[1].substring(1)) != -1 ) {
                     try {
                         apgarMethods[i].invoke(apgar, Integer.parseInt(splitApgarTags[2]));
                     } catch (Exception ex) {
                         Logger.getLogger(APGARTab.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     break;
                 }
             }
             updateRelationalLabel(Integer.parseInt(splitApgarTags[0]),apgar.getSum());      
        }
    }
    
    private void updateRelationalLabel(int apgarInterval, int value) {
        switch (apgarInterval) {
                 case 1:
                     oneMinTotalLabel.setText(new Integer(value).toString());
                     break;
                 case 5:
                     fiveMinTotalLabel.setText(new Integer(value).toString());
                     break;
                 case 10:
                     tenMinTotalLabel.setText(new Integer(value).toString());
                     break;
             }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apgarTimerLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup ciJiOneminButtonGroup;
    private javax.swing.JButton finishButton;
    private javax.swing.ButtonGroup fiveMinActivityButtonGroup;
    private javax.swing.ButtonGroup fiveMinAppearanceButtonGroup;
    private javax.swing.ButtonGroup fiveMinGrimaceButtonGroup;
    private javax.swing.ButtonGroup fiveMinPulsebuttonGroup;
    private javax.swing.ButtonGroup fiveMinRespirationButtonGroup;
    private javax.swing.JLabel fiveMinTotalLabel;
    private javax.swing.ButtonGroup fuSeOneMinButtonGroup;
    private javax.swing.ButtonGroup huXiOneminButtonGroup;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton77;
    private javax.swing.ButtonGroup jiZhangLiOneminButtonGroup;
    private javax.swing.JButton oneMinConfirmButton;
    private javax.swing.JLabel oneMinTotalLabel;
    private javax.swing.JLabel tenMinTotalLabel;
    private javax.swing.ButtonGroup xinLvOneminButtonGroup1;
    // End of variables declaration//GEN-END:variables
}
